# Generated by Django 3.2.4 on 2024-05-01 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
